on:
    release:
        types:
            - created

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: mattdavis0351/actions/docker-gpr@1.3.1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  image-name: tectonic-fontawesome
                  tag: latest
