name: CI to Docker hub
on:
  push:
    branches: [ master ]
jobs:
  push-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: tectonic-cache
      with:
        path: tectonic/**
        key: ${{ hashFiles('tectonic/**') }}
    - name: Set up Docker Buildx
      if: steps.tectonic-cache.outputs.cache-hit != 'true'
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      if: steps.tectonic-cache.outputs.cache-hit != 'true'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      if: steps.tectonic-cache.outputs.cache-hit != 'true'
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./tectonic
        file: ./tectonic/Dockerfile
        push: true
        tags: tommoa/tectonic:latest
    - name: Image digest
      if: steps.tectonic-cache.outputs.cache-hit != 'true'
      run: echo ${{ steps.docker_build.outputs.digest }}
  push-gpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: tectonic-cache
      with:
        path: tectonic/**
        key: ${{ hashFiles('tectonic/**') }}
    - uses: mattdavis0351/actions/docker-gpr@1.3.1
      if: steps.tectonic-cache.outputs.cache-hit != 'true'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: tectonic
        tag: latest
        dockerfile-location: tectonic
